- items: "First Aid Kit" 
  description: "Basic bandages, antiseptic wipes, tweezers, gloves, and tape."  
- items: "Emergency Contact Card" 
  description: "List of important phone numbers and medical information."  
- items: "Pain Relievers" 
  description: "Paracetamol or ibuprofen for minor aches and fever."  
- items: "Emergency Blanket" 
  description: "Thermal blanket to prevent hypothermia."  
- items: "Whistle or Signaling Device" 
  description: "For attracting help when injured or stranded."  
- items: "Medical Gloves" 
  description: "For protection while giving first aid."  
- items: "Flashlight" 
  description: "With extra batteries to see in low light situations."  
- items: "Alcohol or Disinfectant" 
  description: "For wound cleaning and hand sanitation."  
- items: "Gauze Pads and Tape" 
  description: "For dressing larger wounds."  
- items: "Thermometer" 
  description: "For checking fever or illness."  
- items: "Emergency Drinking Water" 
  description: "At least one liter per person per day."  
- items: "Non-perishable Food" 
  description: "Canned or sealed food that won’t spoil."  
- items: "Dust Mask" 
  description: "To help filter contaminated air."  
- items: "Personal Hygiene Items" 
  description: "Tissues, hand sanitizer, feminine products."  
- items: "Battery-powered Radio" 
  description: "To receive emergency broadcasts and updates."  