
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: emergency_guide_app_development

test:
  <<: *default
  database: emergency_guide_app_test

production:
  primary: &primary_production
    <<: *default
    # database: <%= ENV['DATABASE_URL'] %>
    # username: <%= ENV['PG_USERNAME'] %>
    # password: <%= ENV['PG_PASSWORD'] %>
    host: <%= ENV['PG_HOST'] %>
    database: <%= ENV['DATABASE_NAME'] %>
    username: <%= ENV['PG_USERNAME'] %>
    password: <%= ENV['PG_PASSWORD'] %>
    port: <%= ENV['PG_PORT'] || 5432 %>
    <<: *primary_production
    # database: <%= ENV['DATABASE_NAME'] %>
    # migrations_paths: db/cache_migrate
  # queue:
  #   <<: *primary_production
  #   database: emergency_guide_app_production_queue
  #   migrations_paths: db/queue_migrate
  # cable:
  #   <<: *primary_production
  #   database: emergency_guide_app_production_cable
  #   migrations_paths: db/cable_migrate
