
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: emergency_guide_app_development

test:
  <<: *default
  database: emergency_guide_app_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV['PG_HOST'] %>
    database: <%= ENV['DATABASE_NAME'] %>
    username: <%= ENV['PG_USERNAME'] %>
    password: <%= ENV['PG_PASSWORD'] %>
    port: <%= ENV['PG_PORT'] || 5432 %>
    